repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files # prevents giant files from being committed.
      - id: check-ast # simply checks whether the files parse as valid python.
      - id: check-byte-order-marker # forbids files which have a utf-8 byte-order marker.
      - id: check-builtin-literals # requires literal syntax when initializing empty or zero python builtin types.
      - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems.
      - id: check-docstring-first # checks a common error of defining a docstring after code.
      - id: check-executables-have-shebangs # ensures that (non-binary) executables have a shebang.
      - id: check-json # checks json files for parseable syntax.
      - id: check-merge-conflict # checks for files that contain merge conflict strings.
      - id: check-symlinks # checks for symlinks which do not point to anything.
      - id: check-toml # checks toml files for parseable syntax.
      - id: check-vcs-permalinks # ensures that links to vcs websites are permalinks.
      - id: check-xml # checks xml files for parseable syntax.
      - id: check-yaml # checks yaml files for parseable syntax.
      - id: debug-statements # checks for debugger imports and py37+ `breakpoint()` calls in python source.
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
      - id: file-contents-sorter # sorts the lines in specified files (defaults to alphabetical). you must provide list of target files as input in your .pre-commit-config.yaml file.
      - id: mixed-line-ending # replaces or checks mixed line ending.
      - id: name-tests-test # verifies that test files are named correctly.
      - id: sort-simple-yaml # sorts simple yaml files which consist only of top-level keys, preserving comments and blocks.
      - id: trailing-whitespace # trims trailing whitespace.

  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        additional_dependencies: [toml]

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [toml, Flake8-pyproject]

  - repo: https://github.com/pycqa/pylint
    rev: v2.15.6
    hooks:
      - id: pylint

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        additional_dependencies: [toml]
# mypy
# https://github.com/DanielNoord/pydocstringformatter # formats docstrings to follow the Google style.
